#!/usr/bin/env python3
"""
Nginx config generator for Incubator apps.

Generates per-app location blocks in a managed directory.
Each app gets its own .conf file that is included by the main server block.

Usage:
    python scripts/nginx_config.py add myapp 3005
    python scripts/nginx_config.py add myapp 3005 --dry-run
    python scripts/nginx_config.py remove myapp
    python scripts/nginx_config.py list
"""

import argparse
import os
import subprocess
import sys

# Default paths — overridable via env vars
NGINX_APPS_DIR = os.environ.get("NGINX_APPS_DIR", os.path.join(os.path.dirname(__file__), "..", "nginx", "apps"))
NGINX_OVERRIDES_DIR = os.environ.get(
    "NGINX_OVERRIDES_DIR",
    os.path.join(os.path.dirname(__file__), "..", "nginx", "production-apps"),
)
NGINX_CONTAINER = os.environ.get("NGINX_CONTAINER", "aihub-nginx")

LOCATION_TEMPLATE = """\
# Auto-generated by Incubator deploy — {app_name}

# WebSocket (must be before the main location block)
location /{app_name}/_stcore/stream {{
    proxy_pass http://{upstream}:{port}/_stcore/stream;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_read_timeout 86400s;
}}

location /{app_name}/ {{
    proxy_pass http://{upstream}:{port}/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Prefix /{app_name};

    # SSE / streaming
    proxy_set_header Connection '';
    proxy_cache off;
    chunked_transfer_encoding off;

    # Timeouts
    proxy_connect_timeout 10s;
    proxy_read_timeout 300s;
}}
"""


def _config_path(app_name):
    return os.path.join(os.path.abspath(NGINX_APPS_DIR), f"{app_name}.conf")


def _reload_nginx(app_name=None, port=None, action="add", dry_run=False):
    """Reload Nginx to pick up config changes.

    Tries two methods in order:
    1. docker exec <NGINX_CONTAINER> nginx -s reload  — local dev (Docker nginx)
    2. docker run --pid=host alpine kill -HUP <nginx_pid>  — production (system nginx)
       Requires: docker.sock mounted, /run/nginx.pid readable on host.
       The docker daemon resolves the -v path from the HOST filesystem, so this
       works correctly even when called from inside a container.
    """
    if dry_run:
        print(f"  [dry-run] Would reload nginx")
        return True

    # Method 1: Docker nginx container (local dev)
    try:
        subprocess.run(
            ["docker", "exec", NGINX_CONTAINER, "nginx", "-s", "reload"],
            check=True, capture_output=True, text=True,
        )
        return True
    except (subprocess.CalledProcessError, FileNotFoundError):
        pass

    # Method 2: Host system nginx via docker run --pid=host (production).
    # The host docker daemon mounts /run/nginx.pid from the HOST filesystem.
    # --pid=host shares the host PID namespace so kill can reach the nginx master.
    # --privileged is required: CAP_KILL alone is blocked by the default seccomp
    # profile when targeting host PIDs from within a container.
    try:
        subprocess.run(
            [
                "docker", "run", "--rm",
                "--pid=host",
                "--privileged",
                "-v", "/run/nginx.pid:/run/nginx.pid:ro",
                "alpine",
                "sh", "-c", "kill -HUP $(cat /run/nginx.pid)",
            ],
            check=True, capture_output=True, text=True, timeout=30,
        )
        return True
    except Exception as e:
        print(f"  Warning: host nginx reload failed: {e}", file=sys.stderr)

    print("  Warning: No nginx was reloaded", file=sys.stderr)
    return False


def generate_config(app_name, port):
    """Generate the Nginx location block for an app. Returns the config string."""
    # Default to 127.0.0.1 — production uses host nginx (not Docker nginx)
    # so Docker container names don't resolve. This was the #1 cause of
    # deploy failures in the April 2026 session (hit 3 times across 4 apps).
    upstream = os.environ.get("NGINX_UPSTREAM_HOST", "127.0.0.1")
    return LOCATION_TEMPLATE.format(app_name=app_name, upstream=upstream, port=port)


def add_app(app_name, port, dry_run=False):
    """Add an Nginx route for an app. Returns (success, message).

    If a hand-tuned override exists at NGINX_OVERRIDES_DIR/{slug}.conf
    (e.g. nginx/production-apps/marketing-dashboard.conf), use it instead
    of the auto-generated LOCATION_TEMPLATE. Streamlit apps need WS routed
    directly to Streamlit:8501 and a navbar sub_filter that the auto template
    doesn't produce — this preserves those overrides across redeploys.
    """
    override_path = os.path.join(os.path.abspath(NGINX_OVERRIDES_DIR), f"{app_name}.conf")
    if os.path.exists(override_path):
        with open(override_path) as f:
            config = f.read()
        source = f"override ({override_path})"
    else:
        config = generate_config(app_name, port)
        source = "auto-generated"
    path = _config_path(app_name)

    if dry_run:
        print(f"  [dry-run] Would write {path} ({source}):")
        for line in config.splitlines():
            print(f"    {line}")
        print(f"  [dry-run] Would reload Nginx")
        return True, f"Would add route /{app_name}/ → port {port}"

    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(config)
    print(f"  Wrote {path} ({source})")

    reloaded = _reload_nginx(app_name=app_name, port=port, action="add")
    if reloaded:
        return True, f"Added route /{app_name}/ → port {port}"
    return True, f"Added route /{app_name}/ → port {port} (Nginx reload failed — reload manually)"


def remove_app(app_name, dry_run=False):
    """Remove an app's Nginx route. Returns (success, message)."""
    path = _config_path(app_name)

    if not os.path.exists(path):
        return False, f"No config found for {app_name}"

    if dry_run:
        print(f"  [dry-run] Would delete {path}")
        print(f"  [dry-run] Would reload Nginx")
        return True, f"Would remove route /{app_name}/"

    os.remove(path)
    print(f"  Removed {path}")

    _reload_nginx(app_name=app_name, action="remove")
    return True, f"Removed route /{app_name}/"


def list_apps():
    """List all managed app routes. Returns list of (app_name, config_path) tuples."""
    apps_dir = os.path.abspath(NGINX_APPS_DIR)
    if not os.path.isdir(apps_dir):
        return []

    result = []
    for fname in sorted(os.listdir(apps_dir)):
        if fname.endswith(".conf"):
            app_name = fname[:-5]  # strip .conf
            result.append((app_name, os.path.join(apps_dir, fname)))
    return result


def main():
    parser = argparse.ArgumentParser(description="Manage Nginx routes for Incubator apps")
    sub = parser.add_subparsers(dest="command", required=True)

    add_p = sub.add_parser("add", help="Add a route for an app")
    add_p.add_argument("app_name", help="App slug (e.g. 'myapp')")
    add_p.add_argument("port", type=int, help="Port the app listens on")
    add_p.add_argument("--dry-run", action="store_true", help="Print what would happen without making changes")

    rm_p = sub.add_parser("remove", help="Remove an app's route")
    rm_p.add_argument("app_name", help="App slug")
    rm_p.add_argument("--dry-run", action="store_true", help="Print what would happen without making changes")

    sub.add_parser("list", help="List all managed app routes")

    args = parser.parse_args()

    if args.command == "add":
        ok, msg = add_app(args.app_name, args.port, dry_run=args.dry_run)
        print(msg)
        sys.exit(0 if ok else 1)
    elif args.command == "remove":
        ok, msg = remove_app(args.app_name, dry_run=args.dry_run)
        print(msg)
        sys.exit(0 if ok else 1)
    elif args.command == "list":
        apps = list_apps()
        if not apps:
            print("No managed app routes.")
        else:
            for name, path in apps:
                print(f"  /{name}/  →  {path}")


if __name__ == "__main__":
    main()
