#!/usr/bin/env python3
"""
Nginx config generator for AI Hub apps.

Generates per-app location blocks in a managed directory.
Each app gets its own .conf file that is included by the main server block.

Usage:
    python scripts/nginx_config.py add myapp 3005
    python scripts/nginx_config.py add myapp 3005 --dry-run
    python scripts/nginx_config.py remove myapp
    python scripts/nginx_config.py list
"""

import argparse
import os
import subprocess
import sys

# Default paths — overridable via env vars
NGINX_APPS_DIR = os.environ.get("NGINX_APPS_DIR", os.path.join(os.path.dirname(__file__), "..", "nginx", "apps"))
NGINX_CONTAINER = os.environ.get("NGINX_CONTAINER", "aihub-nginx")

LOCATION_TEMPLATE = """\
# Auto-generated by AI Hub deploy — {app_name}

# WebSocket (must be before the main location block)
location /{app_name}/_stcore/stream {{
    proxy_pass http://{upstream}:{port}/_stcore/stream;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_read_timeout 86400s;
}}

location /{app_name}/ {{
    proxy_pass http://{upstream}:{port}/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Prefix /{app_name};

    # SSE / streaming
    proxy_set_header Connection '';
    proxy_cache off;
    chunked_transfer_encoding off;

    # Timeouts
    proxy_connect_timeout 10s;
    proxy_read_timeout 300s;
}}
"""


def _config_path(app_name):
    return os.path.join(os.path.abspath(NGINX_APPS_DIR), f"{app_name}.conf")


PROD_NGINX_SCRIPT = os.environ.get("PROD_NGINX_SCRIPT", "/var/www/aihub-admin/scripts/nginx_production.sh")


def _reload_nginx(app_name=None, port=None, action="add", dry_run=False):
    """Reload Nginx to pick up config changes. Also updates production system Nginx if script exists."""
    # Docker Nginx (for local dev)
    cmd = ["docker", "exec", NGINX_CONTAINER, "nginx", "-s", "reload"]
    if dry_run:
        print(f"  [dry-run] Would run: {' '.join(cmd)}")
        return True

    reloaded = False
    try:
        subprocess.run(cmd, check=True, capture_output=True, text=True)
        reloaded = True
    except (subprocess.CalledProcessError, FileNotFoundError):
        pass

    # Production system Nginx (if script exists on host)
    if app_name and os.path.exists(PROD_NGINX_SCRIPT):
        try:
            prod_cmd = [PROD_NGINX_SCRIPT, app_name, str(port or 0), action]
            subprocess.run(prod_cmd, check=True, capture_output=True, text=True)
            print(f"  Updated production Nginx for {app_name}")
            reloaded = True
        except Exception as e:
            print(f"  Warning: Production Nginx update failed: {e}", file=sys.stderr)

    if not reloaded:
        print("  Warning: No Nginx was reloaded", file=sys.stderr)
    return reloaded


def generate_config(app_name, port):
    """Generate the Nginx location block for an app. Returns the config string."""
    # Inside Docker network, the container name is the upstream host
    upstream = f"aihub-{app_name}"
    return LOCATION_TEMPLATE.format(app_name=app_name, upstream=upstream, port=port)


def add_app(app_name, port, dry_run=False):
    """Add an Nginx route for an app. Returns (success, message)."""
    config = generate_config(app_name, port)
    path = _config_path(app_name)

    if dry_run:
        print(f"  [dry-run] Would write {path}:")
        for line in config.splitlines():
            print(f"    {line}")
        print(f"  [dry-run] Would reload Nginx")
        return True, f"Would add route /{app_name}/ → port {port}"

    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(config)
    print(f"  Wrote {path}")

    reloaded = _reload_nginx(app_name=app_name, port=port, action="add")
    if reloaded:
        return True, f"Added route /{app_name}/ → port {port}"
    return True, f"Added route /{app_name}/ → port {port} (Nginx reload failed — reload manually)"


def remove_app(app_name, dry_run=False):
    """Remove an app's Nginx route. Returns (success, message)."""
    path = _config_path(app_name)

    if not os.path.exists(path):
        return False, f"No config found for {app_name}"

    if dry_run:
        print(f"  [dry-run] Would delete {path}")
        print(f"  [dry-run] Would reload Nginx")
        return True, f"Would remove route /{app_name}/"

    os.remove(path)
    print(f"  Removed {path}")

    _reload_nginx(app_name=app_name, action="remove")
    return True, f"Removed route /{app_name}/"


def list_apps():
    """List all managed app routes. Returns list of (app_name, config_path) tuples."""
    apps_dir = os.path.abspath(NGINX_APPS_DIR)
    if not os.path.isdir(apps_dir):
        return []

    result = []
    for fname in sorted(os.listdir(apps_dir)):
        if fname.endswith(".conf"):
            app_name = fname[:-5]  # strip .conf
            result.append((app_name, os.path.join(apps_dir, fname)))
    return result


def main():
    parser = argparse.ArgumentParser(description="Manage Nginx routes for AI Hub apps")
    sub = parser.add_subparsers(dest="command", required=True)

    add_p = sub.add_parser("add", help="Add a route for an app")
    add_p.add_argument("app_name", help="App slug (e.g. 'myapp')")
    add_p.add_argument("port", type=int, help="Port the app listens on")
    add_p.add_argument("--dry-run", action="store_true", help="Print what would happen without making changes")

    rm_p = sub.add_parser("remove", help="Remove an app's route")
    rm_p.add_argument("app_name", help="App slug")
    rm_p.add_argument("--dry-run", action="store_true", help="Print what would happen without making changes")

    sub.add_parser("list", help="List all managed app routes")

    args = parser.parse_args()

    if args.command == "add":
        ok, msg = add_app(args.app_name, args.port, dry_run=args.dry_run)
        print(msg)
        sys.exit(0 if ok else 1)
    elif args.command == "remove":
        ok, msg = remove_app(args.app_name, dry_run=args.dry_run)
        print(msg)
        sys.exit(0 if ok else 1)
    elif args.command == "list":
        apps = list_apps()
        if not apps:
            print("No managed app routes.")
        else:
            for name, path in apps:
                print(f"  /{name}/  →  {path}")


if __name__ == "__main__":
    main()
